Improvement/maps
Svenbjorn/whatson pull request #100
Opened 2023-10-20 12:22 UTC by paturvita

3 monday items:
https://visitfaroeislands.monday.com/boards/4732496989/pulses/4956373798
https://visitfaroeislands.monday.com/boards/4732496989/pulses/4956374404
https://visitfaroeislands.monday.com/boards/4732496989/pulses/4956375282

TO TEST:
Verify that the map view in whatson events, places and hiking matches the ones in invision and from figma

2023-10-23 10:21 UTC, BartalD commented on views/events/index.html
> +    'pk.eyJ1IjoidmlzaXQtaGFsZCIsImEiOiJjbG52dnJxOTEwM3ljMm1vYThhaTJ3ZDRmIn0.D4HoFio_K0-k3aY_QsruCQ';
Is this a private key?

2023-10-23 10:31 UTC, BartalD commented on views/events/templates/partials/event-list-list.html
> -                    x-text="item.dates.eventDatesDays[0].start_time +' - '+ item.dates.eventDatesDays[0].end_time"
End time has been removed. Maybe ask [Rasmus](@Horib) if there is some other agreement with VFI/Sendistovan?

2023-10-23 10:36 UTC, BartalD commented on views/events/templates/partials/event-list-list.html
> +									<span class="date-day" x-text="item.dates.date.substring(8,10) + '/' + item.dates.date.substring(5, 7)"></span>
Invision shows string format in month. E.g.: 24 DEC instead of 24/12

2023-10-23 11:04 UTC, BartalD requested changes
## Problems
### Left-panel List
![firefox_dW9G38RVc8](https://github.com/Svenbjorn/whatson/assets/26460463/c9d05828-6875-472d-8ede-f36af386ad51)
![firefox_ijwtEx7LPl](https://github.com/Svenbjorn/whatson/assets/26460463/c38f82db-369b-43ba-82b7-c951a37d337d)

- [ ] Date is not in the correct format ([Invision](https://sendistovan.invisionapp.com/console/share/7XFM8NCWDGZ/986217331/play) asks for string in month)
- [ ] Text formatting is off
- [ ] No divider between items on list
- [ ] Scrollbar is visible when list is not scrollable
  - [Rasmus](@Horib) do you have any insights on this? Maybe it should be visible
- [ ] Text-overlay on image should be removed?
- [ ] End-time has been removed (not present in Invision though)
  - [Rasmus](@Horib), do you have any insights here? Maybe VFI asked to have it?

### Map
![firefox_0d3bgSuj8C](https://github.com/Svenbjorn/whatson/assets/26460463/4938aa73-a173-4a34-bfbd-d9d82b66a4e9)

- [ ] Icons on map are ugly
  - If you zoom in on the viewport they become pretty
- [ ] Map is not zoomable with mousewheel
  - I know this is not in the problem description, but it should be a quick fix?

2023-10-26 13:26 UTC, HemmingAskodan requested changes
Rejected for the following reason:

Map's list style overrides the mobile list view. So while the map's list is ok, the mobile list view has gone from OK to NOT OK. The fix here is to separate the stylings, so that the mobile list view gets the old stylings, and the Map's list view gets the new style.

2023-11-10 10:59 UTC, HemmingAskodan commented
![image](https://github.com/Svenbjorn/whatson/assets/54403677/7d00789f-cc64-4bd5-a3f5-c3ef222da71d)

The error above appears when you were in tourism (visitfaroeislands.com) and navigate to whatson. This is because `curl_get_contents` is already declared in the tourism project.
"views\whatson\events.php" did for some reason have this, so I removed it with a commit in this branch.

2023-11-10 11:15 UTC, HemmingAskodan approved these changes

2023-11-13 12:02 UTC, BartalD requested changes
![image](https://github.com/Svenbjorn/whatson/assets/26460463/4dd6752f-7214-45f4-91f2-418023974024)

See my comment above to see the design

Style still doesn't match the design from Sendistovan.
- Date appears to have serifs when they shouldn't
- Months appear to have serifs when they shouldn't
- Alignment of date&month and time seems to be off (might be fixed when fixing bullets above)
- "Place" boldness is not following the design
- Opacity/grayness of fonts is off

2023-11-13 15:15 UTC, BartalD approved these changes
Some text not showing as design. But we have followed the design code.

2023-11-13 15:15 UTC, BartalD commented on events.php
> +												$dateSplit = $this->get_event_date_split($subItem->dates->date, $lang);
formatting

2023-11-13 15:15 UTC, BartalD commented on views/events/templates/partials/event-list-list.html
> -                  ></p>
formatting

2023-11-13 15:15 UTC, BartalD commented on views/events/templates/partials/event-list-list.html
> +									<p class="item-text-excerpt" x-text="item.excerpt"></p>
formatting

2023-11-13 16:08 UTC, merged