Refactoring and Enhancement of Grid Expand Arrow Logic
Svenbjorn/whatson pull request #103
Opened 2023-10-26 14:34 UTC by Horib

### Why:

The primary objective was to implement the grid expand arrow feature for event, place, tour, and hiking grids.

While introducing this feature was the main focus, it presented an opportunity to revisit the underlying codebase. Though not strictly necessary, refactoring was undertaken to make the integration of the new feature smoother. This led to streamlining the codebase, enhancing maintainability, and improving the user experience with the grid expand arrow logic. As a result, we now have an optimized fetch-and-display logic, reduced redundancy, and a consistent expand arrow functionality across the platform.

- Task: [Monday.com](https://visitfaroeislands.monday.com/boards/4732496989/views/112923023/pulses/4533934471)
- Design: [Invision](https://sendistovan.invisionapp.com/console/VFI-Tourism---desktop-ckpjdr19e0hqa010ju83s0gs8/ckpjds4ht0gc0011xa3n7rndz/play)

### Changes Made:

1. **File Renaming:** Changed the main `main.js` to `whatson_main.js` and adjusted its usage to reflect the renaming.
2. **Component Introduction:** Introduced the `expand_arrow` partial component.
3. **Code Refactoring:** Logic has been refactored to be more efficient and modular.
4. **Function Management:** Moved several functions into different files for better code organization.
5. **Documentation:** All newly introduced or refactored functions have been thoroughly documented for clarity.
6. **Feature Addition:** Added `expand_arrow` logic to various sections including places, tours, and others.
7. **Optimization:** Refactored the usage of `createCloseEventHandler` to eliminate duplicate code and streamline its application.

### How to Test:

1. **File Check:** Ensure that `whatson_main.js` is present and that there are no references to the old `main.js`.
2. **Expand Arrow Logic:** Interact with the grid and ensure that the expand arrow logic functions as expected across different sections such as `places`, `tours`, etc.
  - [x] Events
  - [x] Places
  - [x] Tours
  - [x] Hiking 

4. **Functionality:** Verify that the fetch-and-display logic shows the expected results without errors.
  - [x] Events
  - [x] Places
  - [x] Tours
  - [x] Hiking 

6. **URL Behavior:** Interact with the grids and confirm that the URL updates correctly based on the logic described in the `setupCloseEventHandlers` function.
  - [x] Events
  - [x] Places
  - [x] Tours
  - [x] Hiking 

8. **Error Handling:** Ensure that in the absence of required elements or states (like Spruce's `app` store), the appropriate error messages are logged to the console.
9. **Documentation:** Review the provided documentation for clarity and completeness.

2023-10-30 14:23 UTC, HemmingAskodan requested changes
Code is ok.
When code crashes when a fetching a single element, failing gracefully isn't done propperly.
Check tours for scenario.

2023-11-14 13:39 UTC, paturvita approved these changes
Did a quick code review. No breaking issues found, just a couple of comments.
I'm approving this with a lot of comments

I had to make changes to whatson/config/WhatsonApiKeys.class.php:4, because a non-nullable type was being declared as NULL. Maybe just noticed by php 8.
This error did not come from the changes in this pull request, and should not have been in develop, so there seem to be some issues with how versioning is being done.

Comment:
The line: {{include(viewPath~'/modules/gridItem/partials/expand_arrow.twig')}} is a symptom of way too rigid code.  It should be possible to have this line of code in a single place. This is issue is not from this pull request, so it's not grounds for denial, just good to keep in mind.

I was not sure how to test point 9: Error Handling: Ensure that in the absence of required elements or states (like Spruce's app store), the appropriate error messages are logged to the console.
- How should I test this?
- How would I provoke missing information from the user's side?
- What should be tested?

2023-11-14 13:39 UTC, paturvita commented on views/places/js/main.js
- line 983: elsewhere isSubmodule is strictly compared as string "1" or "0", here, we have weak comparison with int 1. May lead to errors and inconsistencies in code

2023-11-14 13:39 UTC, paturvita commented on views/places/templates/partials/gridDOMreplacer.html
Code duplication. This issue has not been caused by this commit, but since duplicate code is added, the issue is getting worse

2023-11-14 13:39 UTC, paturvita commented on views/tours/templates/partials/gridDOMreplacer.html
code duplication is getting worse

2023-11-16 13:19 UTC, Horib commented on views/hiking/js/main.js
Weak comparison is needed, as the server / db returns a number or string value of a number: "1", 1, "0" or 0

Updated documentation

2023-11-16 13:19 UTC, Horib commented on views/events/js/main.js
Weak comparison, as the server / db returns a number or string value of a number: "1", 1, "0" or 0

2023-11-16 13:41 UTC, Horib commented on views/hiking/templates/partials/gridDOMreplacer.html
Improved, thanks for reminding me of good practicies

2023-11-16 13:42 UTC, Horib commented on views/tours/templates/partials/gridDOMreplacer.html
Improved, thanks for reminding me of good practices

2023-11-16 13:50 UTC, merged