Bugfix/event posters
Svenbjorn/whatson pull request #96
Opened 2023-10-02 12:20 UTC by Horib

2023-10-04 12:26 UTC, HemmingAskodan requested changes
![image](https://github.com/Svenbjorn/whatson/assets/54403677/2bae0285-0e1b-4644-b454-405140d09117)
The little line between price range is of in downloaded result.
This goes for 1st, 2nd and 3rd layout.

![image](https://github.com/Svenbjorn/whatson/assets/54403677/84e90349-2f12-442e-9717-d4cdf7feba7b)
Whatson on logo is missing.
This goes for 1st, 2nd and 3rd layout.

2023-10-10 13:51 UTC, BartalD commented on views/posters/js/downloadPoster.js
It could be improved by adding error handling in case the canvas creation or download process fails. Additionally, the function could be refactored to use more descriptive variable names and to separate the canvas creation and download logic into separate functions for better readability.

2023-10-10 14:01 UTC, BartalD commented on views/posters/js/poster-dates.js
> +  const isSingleOccurrence = startDateObj === endDateObj || !endDateObj;
What if the event end after midnight? Will it break this logic?

2023-10-10 14:07 UTC, BartalD commented on views/posters/js/poster-overview.js
> +    if (event.target == modal) {
Shouldn't it be event.target != modal?

2023-10-10 14:20 UTC, BartalD commented on views/posters/js/store-setup.js
Use a separate file for constants: The code defines the posterType, posterColors, monthNames, and monthNamesShort properties directly in the Spruce store. Consider moving these properties to a separate file that defines constants for the poster types, colors, and month names. This can make the code more modular and easier to maintain.

2023-10-10 14:24 UTC, BartalD commented on views/posters/style/_type-abstract.scss
> +      padding: 24px 30px 0 30px;
When do we use px and rem?

2023-10-10 14:26 UTC, BartalD commented on views/posters/style/_type-abstract.scss
> +          font-size: 70px;
px?

2023-10-10 14:26 UTC, BartalD commented on views/posters/style/_type-abstract.scss
> +          line-height: 63px;
px?

2023-10-10 14:26 UTC, BartalD commented on views/posters/style/_type-abstract.scss
> +          padding: 14px;
px?

2023-10-10 14:27 UTC, BartalD commented on views/posters/style/_type-abstract.scss
> +            line-height: 30px;
px

2023-10-10 14:28 UTC, BartalD commented on views/posters/style/_type-abstract.scss
> +            line-height: 46px;
px

2023-10-10 14:38 UTC, BartalD commented on views/posters/style/_type-clean.scss
> +  }
'@extend %common-text-transform' takes longer to write AND read than 'text-transform: uppercase;'. Any specific reason for using a placeholder selector when you only have one variable?

2023-10-10 14:39 UTC, BartalD commented on views/posters/style/_type-clean.scss
When do we use px and rem?

2023-10-10 14:59 UTC, BartalD approved these changes
Very good! Read comments!

2023-10-11 09:48 UTC, BartalD requested changes
#### Overflow Issues
- Price (99999999999999999999999999999999)
- 'Short Description'
- Title - See 'Sjómannadagar' or any longer title
- - The title-box is not aligned as expected

#### Other Issues
- 'End time' does not show
- - This is the case for all date types

#### Testing
- Try using the event: Stóra Bussstoppistøðin hjá Palleba í Trongisvági

2023-10-11 10:37 UTC, Horib commented on views/posters/style/_type-clean.scss
> +  }
Converted it to $uppercase-text-transform: uppercase;

2023-10-11 10:38 UTC, Horib commented on views/posters/style/_type-clean.scss
Posters is a special case, it is for the user to print and download a poster, and for that rem makes no sense as it may break the look of the poster if ie they have set their base px from 16px which 1 rem is, to 10px

2023-10-11 10:50 UTC, Horib commented on views/posters/js/store-setup.js
Good point, but these values are not simple json key value pares, and can not simply be moved out into a json file. and to extract the relevant values may make it more complicated

2023-10-11 14:39 UTC, BartalD commented on views/posters/style/_type-abstract.scss
> +  $uppercase-text-transform: uppercase;
I would argue that this should not be made into a variable.
Are you sure that you want to change ALL of the elements that use this variable?

2023-10-11 14:40 UTC, BartalD commented on views/posters/style/_type-clean.scss
> +  $word-break-break-all: break-all;
Same here

2023-10-11 14:44 UTC, BartalD approved these changes
Very good. Don't use variables when not needed

2023-10-11 15:24 UTC, merged